package com.discord.utilities;

import android.os.Parcel;
import com.discord.api.utcdatetime.UtcDateTime;
import d0.Standard2;
import d0.z.d.Intrinsics3;
import kotlin.Metadata;
import s.b.Parceler;

/* compiled from: Parcelers.kt */
@Metadata(bv = {1, 0, 3}, d1 = {"\u0000\"\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\b\n\u0000\n\u0002\u0010\u0002\n\u0002\b\u0005\bÆ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\f\u0010\rJ\u0017\u0010\u0005\u001a\u00020\u00022\u0006\u0010\u0004\u001a\u00020\u0003H\u0016¢\u0006\u0004\b\u0005\u0010\u0006J#\u0010\n\u001a\u00020\t*\u00020\u00022\u0006\u0010\u0004\u001a\u00020\u00032\u0006\u0010\b\u001a\u00020\u0007H\u0016¢\u0006\u0004\b\n\u0010\u000b¨\u0006\u000e"}, d2 = {"Lcom/discord/utilities/UtcDateTimeParceler;", "Ls/b/a;", "Lcom/discord/api/utcdatetime/UtcDateTime;", "Landroid/os/Parcel;", "parcel", "create", "(Landroid/os/Parcel;)Lcom/discord/api/utcdatetime/UtcDateTime;", "", "flags", "", "write", "(Lcom/discord/api/utcdatetime/UtcDateTime;Landroid/os/Parcel;I)V", "<init>", "()V", "app_productionGoogleRelease"}, k = 1, mv = {1, 4, 2})
/* renamed from: com.discord.utilities.UtcDateTimeParceler, reason: use source file name */
/* loaded from: classes2.dex */
public final class Parcelers implements Parceler<UtcDateTime> {
    public static final Parcelers INSTANCE = new Parcelers();

    private Parcelers() {
    }

    @Override // s.b.Parceler
    public /* bridge */ /* synthetic */ UtcDateTime create(Parcel parcel) {
        return create(parcel);
    }

    public UtcDateTime[] newArray(int i) {
        Intrinsics3.checkNotNullParameter(this, "this");
        throw new Standard2("Generated by Android Extensions automatically");
    }

    @Override // s.b.Parceler
    public /* bridge */ /* synthetic */ void write(UtcDateTime utcDateTime, Parcel parcel, int i) {
        write2(utcDateTime, parcel, i);
    }

    /* JADX WARN: Can't rename method to resolve collision */
    @Override // s.b.Parceler
    public UtcDateTime create(Parcel parcel) {
        Intrinsics3.checkNotNullParameter(parcel, "parcel");
        return new UtcDateTime(parcel.readLong());
    }

    /* renamed from: write, reason: avoid collision after fix types in other method */
    public void write2(UtcDateTime utcDateTime, Parcel parcel, int i) {
        Intrinsics3.checkNotNullParameter(utcDateTime, "$this$write");
        Intrinsics3.checkNotNullParameter(parcel, "parcel");
        parcel.writeLong(utcDateTime.getDateTimeMillis());
    }

    /* renamed from: newArray, reason: collision with other method in class */
    public /* bridge */ /* synthetic */ Object[] m20newArray(int i) {
        return newArray(i);
    }
}
