package com.discord.utilities;

import android.os.Parcel;
import com.discord.api.utcdatetime.UtcDateTime;
import p507d0.Standard2;
import p507d0.p592z.p594d.Intrinsics3;
import p659s.p667b.Parceler;

/* JADX INFO: renamed from: com.discord.utilities.UtcDateTimeParceler, reason: use source file name */
/* JADX INFO: compiled from: Parcelers.kt */
/* JADX INFO: loaded from: classes2.dex */
public final class Parcelers implements Parceler<UtcDateTime> {
    public static final Parcelers INSTANCE = new Parcelers();

    private Parcelers() {
    }

    @Override // p659s.p667b.Parceler
    public /* bridge */ /* synthetic */ UtcDateTime create(Parcel parcel) {
        return create(parcel);
    }

    public UtcDateTime[] newArray(int i) {
        Intrinsics3.checkNotNullParameter(this, "this");
        throw new Standard2("Generated by Android Extensions automatically");
    }

    @Override // p659s.p667b.Parceler
    public /* bridge */ /* synthetic */ void write(UtcDateTime utcDateTime, Parcel parcel, int i) {
        write2(utcDateTime, parcel, i);
    }

    /* JADX WARN: Can't rename method to resolve collision */
    @Override // p659s.p667b.Parceler
    public UtcDateTime create(Parcel parcel) {
        Intrinsics3.checkNotNullParameter(parcel, "parcel");
        return new UtcDateTime(parcel.readLong());
    }

    /* JADX INFO: renamed from: write, reason: avoid collision after fix types in other method */
    public void write2(UtcDateTime utcDateTime, Parcel parcel, int i) {
        Intrinsics3.checkNotNullParameter(utcDateTime, "$this$write");
        Intrinsics3.checkNotNullParameter(parcel, "parcel");
        parcel.writeLong(utcDateTime.getDateTimeMillis());
    }

    /* JADX INFO: renamed from: newArray, reason: collision with other method in class */
    public /* bridge */ /* synthetic */ Object[] m11397newArray(int i) {
        return newArray(i);
    }
}
