name: Decompile Discord

on:
  workflow_dispatch:

jobs:
  decompile-discord:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Get JADX
        uses: dawidd6/action-download-artifact@v9
        with:
          repo: skylot/jadx
          branch: master
          workflow: build-artifacts.yml
          name: .*(?<!win)$
          name_is_regexp: true

      - name: Get Discord
        run: printf "FILE=$(curl -sSL --remote-name --write-out "%{filename_effective}" "https://aliucord.com/download/discord?v=126021")" >> "$GITHUB_ENV"

      - name: Decompile
        run: |
          git rm -qrf decompiled 2>/dev/null || true

          sh */bin/jadx \
            --export-gradle \
            --show-bad-code \
            --fs-case-sensitive \
            --respect-bytecode-access-modifiers \
            --no-inline-methods \
            --no-inline-anonymous \
            --no-inline-kotlin-lambda \
            --use-source-name-as-class-name-alias if-better \
            --output-dir decompiled \
            "$FILE" \
            || true

      - name: Remove Metadata Annotations
        run: find decompiled -type f -name "*.java" -exec sed -i '/@kotlin.Metadata(/d; /@Metadata(/d; /import kotlin.Metadata/d' {} +

      - name: Commit and Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add decompiled
          git commit -m "#$GITHUB_RUN_NUMBER"
          git push

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: decompiled
          path: decompiled
